### PR TITLE
Add a visual monitor for apps

### PR DESCRIPTION
**Pull request by mldk-tech**
#8

### CODE REVIEW

**Comment by mldk-tech** [comment]
Hi @amitaibu -

To get a screenshot for "join our mailing list" app I needed to use the iframe url 

LINK:
 http://shoutout.apps.wixapps.net/widget-new?cacheKiller=1447749091460&compId=comp-iemmphes&deviceType=desktop&instance=T8dxpqxIILlphorhjg1X6IkiZsMpPb66sUL2F5c5Luk.eyJpbnN0YW5jZUlkIjoiMTQwY2JjMGQtYWFjZi1iYTc3LTljOGMtZjMwMjUyNjE4ZTlkIiwic2lnbkRhdGUiOiIyMDE1LTExLTE3VDA4OjMxOjMwLjUzNVoiLCJ1aWQiOm51bGwsInBlcm1pc3Npb25zIjpudWxsLCJpcEFuZFBvcnQiOiI4NC4xMDkuOTAuODgvNjUyOTMiLCJ2ZW5kb3JQcm9kdWN0SWQiOm51bGwsImRlbW9Nb2RlIjp0cnVlLCJvcmlnaW5JbnN0YW5jZUlkIjoiMTQwYzBiZDktN2NlYy05YWU5LWI5MjMtZGYyZmUyNGQxYWRmIiwiYWlkIjoiMmFlNjc5ZGItNzM0Yi00YzAxLWFjOTQtMmRkYmUwNTI4YzY2IiwiYmlUb2tlbiI6IjM3N2VlYjExLTIwYjItZmZlMS0xZDYxLWE4YTIzYzZhNjFhOSIsInNpdGVPd25lcklkIjoiODQ3NzBmNjctZWNiZC00NGI2LWIzNWEtNTg0ZjJkYzE1YWYxIn0&locale=en&viewMode=site&width=275%22 

Screenshot:
browserstack-chrome join-our-mailing-list 1 1200px baseline

**Comment by mldk-tech** [comment]
For the media player image I use the 'http://www.wix.com/demone2/indie-folk' ,form this url I get the media player element for the screenshot image .

Media player screenshot:
browserstack-chrome media-player 1 1200px baseline

**Comment by DavidKohav** [comment]
Do you need any regression for this?

**Comment by mldk-tech** [comment]
The original url have the same visual display

LINK:
http://www.wix.com/website-template/view/html/1692

Template screenshot
browserstack-chrome media-player 1200px

**Comment by mldk-tech** [comment]
Do you need a regression for this?

**Comment by amitaibu** [comment]
Yes, please. movies + regression image

**Pull request closed without merging**
